[package]
name = "Supra Sample"
version = "1.0.0"
authors = []

[addresses]
message_board_addr = "0x1c5acf62be507c27a7788a661b546224d806246765ff2695efece60194c6df05"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dev-dependencies]
